### ISSUE TITLE
Secure api route

### ISSUE THREAD

**Issue by lkrzyzanek** [spaship/operator#71]
Secure api route with redirect policy.
If the configuration is not set, then use http as before.

Example:
```yaml
spec:
  host: <host>
  port:
    targetPort: http-api
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: advanced-content-dev
```
